# Fondos conceptuales temporales, normalizados a la resolucion del proyecto.

image bg oficina = im.Scale("art/concepts/fondo_01_oficina_boceto.png", 1920, 1080)
image bg auto_charco = im.Scale("art/concepts/auto_charco.png", 1920, 1080)
image bg centro_floreria = im.Scale("art/concepts/fondo_02_centro_floreria_boceto.png", 1920, 1080)
image bg interior_floreria = im.Scale("art/concepts/fondo_03_interior_floreria_boceto.png", 1920, 1080)
image bg cocina_fria = im.Scale("art/concepts/fondo_04_cocina_luz_fria_boceto.png", 1920, 1080)
image bg cocina_calida = im.Scale("art/concepts/fondo_05_cocina_luz_calida_boceto.png", 1920, 1080)
image bg habitacion_gabriel = im.Scale("art/concepts/fondo_06_habitacion_gabriel_boceto.png", 1920, 1080)
image bg habitacion_gabriel_oscuro = im.Scale("art/concepts/fondo_07_habitacion_gabriel_rosa_boceto.png", 1920, 1080)
image bg parada_lluvia = im.Scale("art/concepts/fondo_08_parada_lluvia_boceto.png", 1920, 1080)
image bg interior_colectivo = im.Scale("art/concepts/fondo_09_interior_colectivo_boceto.png", 1920, 1080)
image bg entrada_casa = im.Scale("art/concepts/fondo_10_entrada_casa_boceto.png", 1920, 1080)
image bg banio = im.Scale("art/concepts/fondo_11_banio_boceto.png", 1920, 1080)
image bg habitacion_lucas = im.Scale("art/concepts/fondo_12_habitacion_lucas_boceto.png", 1920, 1080)
image bg cursor_pantalla = im.Scale("art/concepts/fondo_13_cursor_pantalla_boceto.png", 1920, 1080)
image bg papeles_escritorio = im.Scale("art/concepts/fondo_13b_papeles_escritorio_boceto.png", 1920, 1080)
image bg bondi_primer_plano = im.Scale("art/concepts/bondi_llegando.png", 1920, 1080)

# TODO Arte: reemplazar por imagen del colectivo llegando a la parada.
image bg bondi_llegando = Solid("#000")
image bg moneda_escritorio = im.Scale("art/concepts/moneda_escritorio.png", 1920, 1080)
image bg juguetes_lucas = im.Scale("art/concepts/juguetes_lucas.png", 1920, 1080)
image bg moneda_volando = im.Scale("art/concepts/moneda_volando_escritura.png", 1920, 1080)
image bg moneda_volando_flashback = im.Scale("art/concepts/moneda_volando_flashback.png", 1920, 1080)
image bg primer_plano_flor = im.Scale("art/concepts/primer_plano_flor.png", 1920, 1080)
image bg reloj_18hs = im.Scale("art/concepts/reloj_18hs.png", 1920, 1080)
image bg reloj_21hs = im.Scale("art/concepts/reloj_21hs.png", 1920, 1080)
# TODO Arte: reemplazar por efecto visual de barro/agua salpicando a Gabriel.
image bg salpicadura_barro = Solid("#000")
